export const projects = [
  {
    title: "Face Identity Computer Vision Project",
    startPeriod: "11/2021",
    endPeriod: "12/2021",
    descriptions: [
      "Develop a face identification system with monolith Django Rest Framework API (server side application) to store data and manage it with SQL and utilise AWS for cloud storage on image capture.",
      `Utilise OpenCV as the client side application that will interact with user, capture/learn new data (face) that is not yet exist in the “computer’s memory”, and recognize faces that the computer has “memorized”`,
      "Integrate Google Voice Assistant on the software to interact with user verbally.",
      "Utilise utilise multi threads system to run different tasks at the same time",
      "Use message queue to pass package of information between threads",
    ],
    type: "programming",
    image: "/Images/face-identity.png",
    links: [],
  },
  {
    title: "Kinesis Project",
    startPeriod: "10/2021",
    endPeriod: "Present",
    descriptions: [
      "Develop a fitness mobile apps in a test-driven development environment, and develop CI/CD Pipeline with HerokuCI.",
      "Utilise React Native for the Mobile UI Framework, monolith architecture with authentication on the backend with Express (Typescript), and MongoDB Atlas as the database technology",
      "UI Framework such as UI Kitten, and React-Native Elements are utilise to develop the whole mobile app's Front-End",
    ],
    type: "programming",
    image: "/Images/kinesis.png",
    links: [],
  },
  {
    title: "Personal Portfolio React Web App",
    startPeriod: "12/2020",
    endPeriod: "Present",
    descriptions: [
      "Developing a personal portfolio with React.",
      "Develop an interactive web app for a personal introduction.",
      "Improve experiences and familiarities with React, Javascript, CSS, HTML, and UI/UX design.",
    ],
    type: "programming",
    image: "/Images/personal.png",
    links: [],
  },
  {
    title: "Unimelb B-SCI Course Planner React Web App Project",
    startPeriod: "11/2020",
    endPeriod: "Present",
    descriptions: [
      "Collaboration project in developing a web app application for the University of Melbourne's Bachelor of Science program courses related to the major taken.",
      "A course planner that utilizes a flowchart system operation.",
      "Utilize REST principal in accessing the University of Melbourne's Bachelor of Science courses and majors (e.g. accessing subjects API data).",
      "Utilize Javascript, HTML, CSS, and React in developing the web app.",
    ],
    type: "programming",
    image: "/Images/planar.png",
    links: [],
  },
  {
    title: "Artist Express Web App Development Project",
    startPeriod: "10/2020",
    endPeriod: "12/2020",
    descriptions: [
      "Building an Express.js web app by utilizing HTML, EJS, CSS (Custom style sheet, and Bootstrap 5 ), and JavaScript.",
      "Develop a front-end and back-end client-server.",
      "Develop a database for all registered users/owners, reviews, and all available music albums via MongoDB/mongoose ODM database (NoSQL database).",
      "Enhance programming knowledge and experiences through a web application development.",
      "Personal project to expand my audience and network.",
      "A website that introduces my self as a music producer.",
    ],
    type: "programming",
    image: "/Images/azure-web.png",
    links: [],
  },
  {
    title: "A Two-Level Tower Game Project (Java OOP)",
    startPeriod: "05/2020",
    endPeriod: "06/2020",
    descriptions: [
      "Develop a two-level tower game by utilizing Java language and bagel library.",
      "Design a UML diagram of the proposed game design.",
      "Utilize and integrate object-oriented programming.",
      "Mathematical modelling applied for some motions in the game.",
    ],
    type: "game",
    image: "/Images/tower.png",
    links: [],
  },
  {
    title: "Monthly Music Single and EP Album Project",
    startPeriod: "04/2020",
    endPeriod: "Present",
    descriptions: [
      "Produce and release a single or an EP project each month.",
      "Receiving offers to be promoted by several musical blogs and labels.",
    ],
    type: "music",
    image: "/Images/music.png",
    links: [],
  },
  {
    title: "Warman Project",
    startPeriod: "03/2020",
    endPeriod: "05/2020",
    descriptions: [
      "A team of 4 that construct and develop a competitive autonomous device to compete in Warman Competition 2020.",
      "The device was appreciated and predicted to win the competition or at least secure a top 5 position",
      "A productive and efficient team collaboration project",
      "Responsible for designing delivery/propulsion systems of the device",
      "Develop engineering drawings for cart mechanism, mecanum wheels, 3D models and simulations of the system",
      "Combining the subsystem with the other subsystems",
      "Develop a risk management analysis, and budgeting on the design",
      "Deliver a professional presentation to the client (professional Engineer)",
    ],
    type: "engineering",
    image: "/Images/warman.png",
    links: [],
  },
  {
    title: "Rainfall Cycle",
    startPeriod: "05/2019",
    endPeriod: "06/2019",
    descriptions: [
      "Develop a data structure algorithm to simulate climate change data analysis (C programming languages)",
      "Statistical analysis annual rainfall cycle",
      "Utilize Kendall's tau mathematical model to compute trend analysis",
      "Data representation to plot climate changes in data analysis",
    ],
    type: "programming",
    image: "/Images/rainfall.png",
  },
  {
    title: "Drone Delivery Path Optimization",
    startPeriod: "04/2019",
    endPeriod: "05/2019",
    descriptions: [
      "Simulate drones delivery data with the C programming language",
      "Integrate mathematical modeling to calculate battery consumption depending on the package that is delivered",
      "Mathematical modeling to develop algorithm on deciding the most optimum delivery path with least battery consumptions",
      "Develop sorting algorithms for multiple purposes",
    ],
    type: "programming",
    image: "/Images/drones.png",
    links: [],
  },
  {
    title: "Art Exhibition",
    startPeriod: "06/2016",
    endPeriod: "03/2017",
    descriptions: [
      "Develop 7 artworks for Sekolah Pelita Harapan Sentul City (SPH SC) art exhibition event.",
      "Completed 2 sculptures, 3 paintings, and 2 photographs.",
      "Improving technical skills and disciplines.",
    ],
    type: "art",
    image: "/Images/art-exhibition.jpg",
    links: [],
  },
];

export const experiences = [
  {
    title: "Summer Program Student Mentor",
    companyName: "Sekolah Pelita Harapan",
    type: "Internship",
    startPeriod: "05/2015",
    endPeriod: "06/2015",
  },
  {
    title: "Undergraduate Student",
    companyName: "Univeristy of Melbourne",
    type: "Full-time",
    startPeriod: "07/2017",
    endPeriod: "07/2020",
  },
  {
    title: "Music Producer (Azure Gaze)",
    companyName: "DistroKid",
    type: "Self-employed",
    startPeriod: "04/2020",
    endPeriod: "Present",
  },
];

export const educations = [
  {
    title: "Sekolah Pelita Harapan Sentul City",
    degree: "High School Diploma",
    startYear: "2014",
    endYear: "2017",
    logo: "/Images/sph.ico",
    image: "/Images/sph.png",
    descriptions: [
      "International Baccalaureate based education",
      "High School/Secondary Diplomas and Certificates",
    ],
    courses: [
      "Physics HL",
      "Math HL",
      "Business Management HL",
      "English B HL",
      "Indonesian A SL",
      "Art SL",
    ],
  },
  {
    title: "University of Melbourne",
    degree: "Bachelor of Science - BS, Mechanical Systems",
    startYear: "2017",
    endYear: "2020",
    logo: "/Images/unimelb.ico",
    image: "/Images/unimelb.png",
    descriptions: [
      "3 years full-time studies majored in Mechanical Systems",
      "Involved in Warman Project",
      "Design an engineering device and create a professional engineering drawing and 3d simulation",
      "Develop knowledge in engineering and risk management",
    ],
    courses: [
      "Mechanical System Designs(MCEN30021)",
      "System Modelling and Simulation(MCEN30020)",
      "Thermodynamics and Fluid mechanics(MCEN30018)",
      "Mechanics, and Materials(MCEN30017)",
    ],
  },
  {
    title: "RMIT University",
    degree: "Master of Engineering, Robotics and Mechatronics Engineering",
    startYear: "2020",
    endYear: "Present",
    logo: "/Images/rmit.ico",
    image: "/Images/rmit.png",
    descriptions: [
      "2 years master full-time studies specialized robotics and mechatronics engineering",
      "Develop professional practices in engineering industry",
      "Trained to enhance communication, management and flexibility in different work environments",
    ],
    courses: [
      "MANU2453(Advanced Robotic Systems)",
      "MANU2451(Advanced Mechatronics System Design)",
      "EEET1262(Real Time Systems Design)",
      "EEET2223(Real Time Estimation & Control)",
      "OENG1116(Modelling and Simulation)",
      "EEET1368(Advanced Control Systems)",
    ],
  },
];

export const workExperiences = [
  {
    title: "Software Developer",
    companyName: "Laputan Software",
    location: "Melbourne",
    start: "April 2022",
    end: "Present",
    startYear: "2022",
    endYear: "Present",
    logo: "/Images/laputan-software.ico",
    image: "/Images/laputan-software.png",
    descriptions: [
      "Working with more than 5 technologies such as React, Redux-Saga, Typescript, GraphQL, Docker, and more.",
      "Develop serverless REST API and AWS lambda functions with design patterns that improve the development process by 20%.",
    ],
  },
  {
    title: "Junior Full-stack Software Engineer",
    companyName: "University of Melbourne",
    location: "Melbourne",
    start: "March 2022",
    end: "Present",
    startYear: "2022",
    endYear: "Present",
    logo: "/Images/unimelb.ico",
    image: "/Images/unimelb.png",
    descriptions: [
      "Developed software for PeakHour Urban Technologies startup company and worked with more than 5 technologies such as Typescript, AWS, Docker, NestJS, React, etc.",
      "Data processing on large datasets to build server-side ML model with a performance 48.07% faster than expected.",
      "Deploy  more than 4 features for both server-side and client-side.",
    ],
  },
  {
    title: "Software Developer Intern (Front End Team Lead)",
    companyName: "Reesby",
    location: "Melbourne",
    start: "December 2021",
    end: "April 2022",
    startYear: "2021",
    endYear: "2022",
    logo: "/Images/reesby.ico",
    image: "/Images/reesby.png",
    descriptions: [
      "Selected as the top-performing intern 4 times by the technology team.",
      "Software testing for bugs and operating speed.",
      "Bugs fixing and documenting processes to increase efficiency by 18%.",
    ],
  },
  {
    title: "Software Developer Intern (Front End)",
    companyName: "Reesby",
    location: "Melbourne",
    start: "June 2021",
    end: "December 2021",
    startYear: "2021",
    endYear: "2021",
    logo: "/Images/reesby.ico",
    image: "/Images/reesby.png",
    descriptions: [
      "Developed a marketing tool that enables the organisation to reach a total of 24,786 clients for an organisation’s event with one click of a button with React and Redux",
      "Increase the delivery rate by 25% by developing a CI/CD pipeline from version control to AWS.",
      "Working on the API design with backend team for React and Redux state data struct integration",
      "Develop smart data management and type classification parsing system which increase customer data management 30% faster.",
    ],
  },
];

export const artworks = [
  {
    title: "Lost",
    dateCreated: "13/03/2021",
    releaseDate: "14/03/2021",
    tracksNumber: 2,
    spotify:
      "https://open.spotify.com/album/2OrqjmzTWak9PlC7GnaVxm?si=Xx9SkwDHStO9vW_cQw98Ig",
    appleMusic: "https://music.apple.com/us/album/lost-single/1558363703",
    soundCloud: "https://soundcloud.com/azuregaze/sets/lost",
    trackTitles: ["lost", "lakeside"],
  },
  {
    title: "Within the Mist",
    dateCreated: "26/12/2020",
    releaseDate: "31/12/2020",
    tracksNumber: 3,
    spotify:
      "https://open.spotify.com/album/3VcK7fN34jgbEzbiyP5Nwa?si=810TbDJfTdSHxaUfzsbacA",
    appleMusic:
      "https://music.apple.com/us/album/within-the-mist-single/1547507932",
    soundCloud: "https://soundcloud.com/azuregaze/sets/within-the-mist",
    trackTitles: ["within the mist", "sanpo", "by your side"],
  },
  {
    title: "Cold Morning",
    dateCreated: "01/11/2020",
    releaseDate: "03/11/2020",
    tracksNumber: 2,
    spotify:
      "https://open.spotify.com/album/2gRb8eXpOQRlGweJBzLsmj?si=m6x39ZkVSQKiV0B00_jDyA",
    appleMusic:
      "https://music.apple.com/us/album/cold-morning-single/1538670268",
    soundCloud: "https://soundcloud.com/azuregaze/sets/cold-morning",
    trackTitles: [
      "walking through the cold morning breeze",
      "met her at the station",
    ],
  },
  {
    title: "waterfall",
    dateCreated: "17/01/2020",
    releaseDate: "13/10/2020",
    tracksNumber: 1,
    spotify:
      "https://open.spotify.com/album/5ojtNrVgRB6n9qVzpaBfLx?si=6zBwuRQoToWZTZ5hYw7tUw",
    appleMusic: "https://music.apple.com/us/album/waterfall-single/1535671046",
    soundCloud: "https://soundcloud.com/azuregaze/waterfall",
    trackTitles: ["waterfall"],
  },
  {
    title: "City Night Walk",
    dateCreated: "03/09/2020",
    releaseDate: "10/09/2020",
    tracksNumber: 3,
    spotify:
      "https://open.spotify.com/album/7BneYOQpyBcBHdO7oBekjs?si=0GSSVujzSnSiYoZpmldwQA",
    appleMusic:
      "https://music.apple.com/us/album/city-night-walk-single/1531757712",
    soundCloud: "https://soundcloud.com/azuregaze/sets/city-night-walk",
    trackTitles: ["city night walk", "on the way home", "suddenly sleepy"],
  },
  {
    title: "springtime",
    dateCreated: "19/01/2020",
    releaseDate: "03/09/2020",
    tracksNumber: 1,
    spotify:
      "https://open.spotify.com/album/4Jyyu3vi32weEbgYQSjEDd?si=YbRSEWlzRgGxHlSsN5nqAw",
    appleMusic: "https://music.apple.com/us/album/springtime-single/1530987506",
    soundCloud: "https://soundcloud.com/azuregaze/springtime",
    trackTitles: ["springtime"],
  },
  {
    title: "Wander",
    dateCreated: "18/07/2020",
    releaseDate: "29/07/2020",
    tracksNumber: 2,
    spotify:
      "https://open.spotify.com/album/3PG95oQgYdBxp34nWhq0dO?si=MiIg6DXMTVOTta_ipdf5tg",
    appleMusic: "https://music.apple.com/us/album/wander-single/1525609992",
    soundCloud: "https://soundcloud.com/azuregaze/sets/wander",
    trackTitles: ["Wander", "Pluie de la Ville"],
  },
  {
    title: "Sleep Deprived",
    dateCreated: "07/07/2020",
    releaseDate: "15/07/2020",
    tracksNumber: 1,
    spotify:
      "https://open.spotify.com/album/1iL37wBwCXOVZtilnNMvvK?si=E9uY-ETPQmOurEACpritxw",
    appleMusic:
      "https://music.apple.com/us/album/sleep-deprived-single/1523865684",
    soundCloud: "https://soundcloud.com/azuregaze/sleep-deprived",
    trackTitles: ["Sleep Deprived"],
  },
  {
    title: "Reminiscing",
    dateCreated: "23/06/2020",
    releaseDate: "06/07/2020",
    tracksNumber: 1,
    spotify:
      "https://open.spotify.com/album/1YNASOH8I4Uco64V4lmfD7?si=6QbnmPAvQkuo9hPHJ1lVZQ",
    appleMusic:
      "https://music.apple.com/us/album/reminiscing-single/1522701238",
    soundCloud: "https://soundcloud.com/azuregaze/reminiscing",
    trackTitles: ["Reminiscing"],
  },
  {
    title: "Hey There",
    dateCreated: "03/05/2020",
    releaseDate: "14/05/2020",
    tracksNumber: 0,
    spotify:
      "https://open.spotify.com/album/26hrFc2urW7yQlpCZljzgo?si=cs4YtxrsSLOR07Z0pFRZww",
    appleMusic: "https://music.apple.com/us/album/hey-there-single/1513381692",
    soundCloud: "https://soundcloud.com/azuregaze/hey-there",
    trackTitles: ["Hey There"],
  },
  {
    title: "Blue Nostalgia",
    dateCreated: "27/12/2019",
    releaseDate: "03/05/2020",
    tracksNumber: 5,
    spotify:
      "https://open.spotify.com/album/5TykcNF7HwmCV3mMc9c5MK?si=Pv-kAa-rSF6j5axYXaxKjw",
    appleMusic: "https://music.apple.com/us/album/blue-nostalgia-ep/1511766216",
    soundCloud: "https://soundcloud.com/azuregaze/sets/blue-nostalgia",
    trackTitles: [
      "Love in Tokyo",
      "Rain and Cigarettes",
      "Funny Romance",
      "Blue Nostalgia",
      "Lovesick",
    ],
  },
];
